name: 'Interactive rush.js'
description: 'Interactive rush.js integration'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: '__repo'
    - run: npm install; node ./lib/github-action.js
      shell: pwsh
      working-directory: ${{ github.action_path }}