name: 'Interactive rush.js'
description: 'Interactive rush.js integration'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: '__repo'
        ref: ${{ github.event.pull_request.head.sha }}
    - run: |
        git fetch -c protocol.version=2 fetch --no-tags --progress --no-recurse-submodules --depth=1 origin ${{ github.event.pull_request.base.sha }}
        git branch -f ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.base.sha }}
        git branch -f ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.head.sha }}
        git checkout ${{ github.event.pull_request.head.ref }}
      shell: pwsh
      working-directory: '__repo'
    - run: npm install; node ./lib/github-action.js
      shell: pwsh
      working-directory: ${{ github.action_path }}